sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
    - pip install prettytable
    - pip install pytz
    - pip install datetime
    - pip install tqdm
    - pip install coloredlogs
    - pip install requests
    - pip install nose
    - pip install pycodestyle
    - pip install tox
    - pip install pyyaml
script:
    - pycodestyle --max-line-length=180 .
    - nosetests -s
    
deploy:
  provider: pypi
  user: "lewzylu"
  password:
    secure: "L0XLFLP+UK9H/JbUFARFjxAz6tB8B1KJ1ko0KoKOtvr4L4/SCyolQrzkKIHaPA5BR3C564ZMsXEfuvhfNf7v0U1FcNE9FNy02wCwmRWM48uVj5fMw5YW5rrgPdnY3cwjvehi+8b0MMzoAeWPCUVqKA7whTZXr9Tn3EkbDXskfV6iAf+ztbDuIWXYnWKbdJ3y/LhyFqK3k56pRuqzYpADORhKepLQRLFzXG/f69bx38e1CkMe7Tqa0HHCA9x5u1C9fgOpfEbw4jW00An4FD2RlQfp2rlvO2UaP2fpD8zaTI7zlN4nYxGg17AvUL2VzaUwKlFe+twFrY0XftFn+JKpbolcZvnsHiUlxA2eNHTU2D9LkCnGheMJB/KgVaVXMq+3IxCyM1zfmnP/UF5XUiNsFX7FxlTaNlc/DHyfvbiv39/inC5nixgnYjhPu/auBRHJJtDG00/7RWhP4ETTkRS/YQjDuym7iu5OjiwFp5UXfEo5w3jLRTHBa5afPtUnTLtTRr4+5qz8dxUCM+kzNHVJsy+A9pfwRbavwmS4lmn9oE5xW6fd4EnZbJ+OKa7lmbDtI3T1z/16EnYsT1yEIgHuN1RZFPnIDP4w3GH2qIiYgMSG267vIG2OjQfitlbSDwtLs4XClngzrkz34LqPhPUOvqET3qU2EK4tTeNY4hBtJzc="
  on:
    tags: true
    branch: master
