sudo: false
language: python

python:
  - "2.7"

install:
    - pip install prettytable
    - pip install pytz
    - pip install datetime
    - pip install tqdm
    - pip install coloredlogs
    - pip install requests
    - pip install nose
    - pip install pep8
    - pip install tox
script:
    - pep8 --max-line-length=180
    - nosetests -s
